[features]
resolution = true
seeds = false
skip-lint = false

[programs.devnet]
dblt_lending = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS" # REPLACE WITH YOUR ACTUAL ID

[programs.localnet]
dblt_lending = "AXdWprPxpre9hbCJpryiwktSYgBKKaoFHHTufwGRTfLQ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
# cluster = "devnet"
# wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "cargo test"