[toolchain]
anchor_version = "0.30.1"
solana_version = "3.1.10"

[features]
resolution = true
skip-lint = false

[programs.devnet]
generic_record = "EL1vHbKVUwHDneBhwqC28o1xrzNSx2Dk2AmxytfQpote"
dblt_lending = "22bmZ5cp4DdUitMt8okSwygWP1f9oWpG6zXGkVBrgCtV"

[programs.localnet]
generic_record = "EL1vHbKVUwHDneBhwqC28o1xrzNSx2Dk2AmxytfQpote"
dblt_lending = "22bmZ5cp4DdUitMt8okSwygWP1f9oWpG6zXGkVBrgCtV"

[provider]
cluster = "localnet"
wallet = "keys/localnet/authority.json"

[scripts]
test = "make test-programs"

[hooks]
